### ISSUE TITLE
Is this package now supported in the spring environment

### ISSUE THREAD

**Issue by eyesli** [jenkinsci/groovy-sandbox#118]
### What feature do you want to see added?

This package supports scripting security in the spring environment

```[tasklist]
### Tasks
```

**Comment by eyesli** [comment]
Or is there any alternative thanks

**Comment by dwnusbaum** [comment]
@eyesli, no I would not recommend using this library directly for anything you are working on. I'm not sure about any alternative libraries, but in general I would be wary of in-process sandboxing.
