### ISSUE TITLE
"Annonymous inner class constructor call "- While intercepting it cannot find constructors from groovy.lang.MetaClassImpl while using the latest version 4

### ISSUE THREAD

**Issue by stefanroganovicnq** [jenkinsci/groovy-sandbox#122]
### Jenkins and plugins versions report

Our System is running on with:
Java 17
Spring 6
GroovyAll 4.0.22
....
..
and all other compatibile libraries

### What Operating System are you using (both controller, and any agents involved in the problem)?

Our System is running on with:
Java 17
Spring 6
GroovyAll 4.0.22
....
..
and all other compatibile libraries

### Reproduction steps

For this kind of String which content is basically a groovy code:
     String script = 
            "def myObject = new MyClass() { \n" +
            "    String myMethod() {\n" +
            "        return \"Hello from anonymous class!\"\n" +
            "    }\n" +
            "}\n" +
            "myObject.myMethod()\n" +
            "class MyClass {\n" +
            "    String myMethod() {\n" +
            "        return \"Hello world!\"\n" +
            "    }\n" +
            "}\n";

When we try first to validate and parseClass by using the groovy code everything works fine untill we come to the point of execution. So to speak first based on this String we will create Script instance from groovy lib, which inside of it has run() method which will then trigger whole execution part. Inside the execution part we are triggering also Interceptors. Our main problem is that in groovy.lang.MetaClass while intercepting Consturctors calls we cannot find constructors and  groovy.lang.MetaClassImpl will return empty array list of Constructors and Groovy will Throw GroovyRuntimeException - Could not find matching constructors.. From debug point of view, debug path is 100% same with versoin 2 and latest version 4, but at one point with versoin groovy version 2 it is returning constructors and at same place with version 4 it is returning empty array of constructors.I will post full stack trace in next picture:
![image-2024-08-07-11-55-09-947](https://github.com/user-attachments/assets/ff73cfda-f30d-4ef4-9d22-e324a2e2024a)

If you are confused what is MAF_SRC_5043206438346436, its just a customized name by my implementatotion  while creating GroovySourceCode object and its directly related name parameter. 
      final GroovyCodeSource groovyCodeSource =
          new GroovyCodeSource(codeSource, name, GroovyShell.DEFAULT_CODE_BASE);

This is the part of the Checker.java class where it is calling checkConstructor

    public static Object checkedConstructor(Class _type, Object[] _args) throws Throwable {
        return new VarArgInvokerChain(_type) {
            public Object call(Object receiver, String method, Object... args) throws Throwable {
                if (chain.hasNext())
                    return chain.next().onNewInstance(this,(Class)receiver,args);
                else
                    // I believe the name is unused
                    return fakeCallSite("<init>").callConstructor((Class)receiver,args);
            }
        }.call(_type,null,fixNull(_args));
    }

### Expected Results

It should match the constructors.

### Actual Results

Could not find matching constructors.

**Comment by stefanroganovicnq** [comment]
public static Object checkedConstructor(Class _type, Object[] _args) throws Throwable {
        return new VarArgInvokerChain(_type) {
            public Object call(Object receiver, String method, Object... args) throws Throwable {
                if (chain.hasNext())
                    return chain.next().onNewInstance(this,(Class)receiver,args);
                else
                    // I believe the name is unused
                    return fakeCallSite("<init>").callConstructor((Class)receiver,args);
            }
        }.call(_type,null,fixNull(_args));
    }


this is the method from Checker.java class which exists in stack trace, and its is going through  return fakeCallSite("<init>").callConstructor((Class)receiver,args);

**Comment by dwnusbaum** [comment]
@stefanroganovicnq Please see the README for this library, if you are using this library directly it is extremely likely that your sandbox can be trivially bypassed, doubly so if you are not using the exact version of Groovy that is used by current versions of Jenkins, and I would really encourage you to stop using it and find some other library which is actually designed to be used outside of the Jenkins project or better yet, use a totally different approach rather than attempting in-process sandboxing like this: https://github.com/jenkinsci/groovy-sandbox/blob/master/README.md.

As far as your reported issue, your script works fine in a test case here. It seems you have fully forked the library, e.g. your package names are distinct, so my guess is that the problem is related to whatever you might have changed, or your custom interceptors.
