### ISSUE TITLE
Non existing pictures referenced in the dependencies page

### ISSUE THREAD

**Issue by laurentvaills** [jenkinsci/groovy-sandbox#25]
While browsing on the groovy-sandbox website, I noticed that on the page http://groovy-sandbox.kohsuke.org/dependencies.html some pictures were "broken".
The following URLs referenced by this page return 404 : 
- http://groovy-sandbox.kohsuke.org/images/icon_success_sml.gif
- http://groovy-sandbox.kohsuke.org/images/icon_success_sml.gif

**Comment by dwnusbaum** [comment]
Thanks for reporting this, sorry no one ever took a look at it earlier! I just removed all of the content on http://groovy-sandbox.kohsuke.org/ and replaced it with a redirect to the GitHub page, so I am going to close this issue.
