### ISSUE TITLE
java.lang.ArrayStoreException: org.kohsuke.groovy.sandbox.SandboxTransformer

### ISSUE THREAD

**Issue by AshishKothari** [jenkinsci/groovy-sandbox#28]
Hello sir I m getting following error:
`java.lang.ArrayStoreException: org.kohsuke.groovy.sandbox.SandboxTransformer
java.lang.ArrayStoreException: org.kohsuke.groovy.sandbox.SandboxTransformer`

My code is:
`CompilerConfiguration cc = new CompilerConfiguration();
SandboxTransformer st = new SandboxTransformer();               
cc.addCompilationCustomizers(st);`

Getting error at line 3rd line. 

Can you suggest me what should I do?

**Comment by jglick** [comment]
Probably you are trying to treat an object as an array here.
