### ISSUE TITLE
filter of sandbox is inactive 

### ISSUE THREAD

**Issue by Sunrry** [jenkinsci/groovy-sandbox#49]
I want to use groovy-sandbox in my project ( java project), so I create "GroovySandbox", the source code is as follow:
`
public class GroovySandbox extends GroovyValueFilter {

    @Override
    public Object filter(Object o) {
        throw new SecurityException("Denied!");
    }
}
`

And I register the sandbox in my code like : 
`
CompilerConfiguration compilerConfiguration = new CompilerConfiguration();
        compilerConfiguration.addCompilationCustomizers(new SandboxTransformer());
        GroovyShell groovyShell = new GroovyShell(compilerConfiguration);
        new GroovySandbox().register();
        groovyShell.evaluate("return true;");
`

While I debug my code, and I found it can never stop into filter method, and the exception is not thrown,  is there anything I missed ?
Thanks !

**Comment by dwnusbaum** [comment]
@Sunrry I am not sure why things might not have been working for you, maybe you needed to test with a more complicated script that contained property access or a method call or something? Either way, I would discourage you from using this library for any new development, please see the recently-updated README. I am going to go ahead and close this issue.

**Comment by brandaomarcos** [comment]
fg

> @Sunrry I am not sure why things might not have been working for you, maybe you needed to test with a more complicated script that contained property access or a method call or something? Either way, I would discourage you from using this library for any new development, please see the recently-updated README. I am going to go ahead and close this issue.

Is there any other lib that we can use to replace it?
