### ISSUE TITLE
Release 1.20 doesn't seem to be available in Maven Central Repository

### ISSUE THREAD

**Issue by jlussagnet** [jenkinsci/groovy-sandbox#52]
See https://mvnrepository.com/artifact/org.kohsuke/groovy-sandbox.

**Comment by jglick** [comment]
Security releases are not currently mirrored to Central, sorry. Use the Jenkins Artifactory.

**Comment by dwnusbaum** [comment]
To expand on that, the current maintainers of this library only use it in the context of Jenkins, and for the most part the only work that happens is security fixes, so this will probably happen more and more often. I will try to update the README to mention that any users of the library should use `https://repo.jenkins-ci.org/releases/`, and that only historical releases are available on Maven central.
