### ISSUE TITLE
It's not obvious that https://repo.jenkins-ci.org/public/ needs to be configured as a repository

### ISSUE THREAD

**Issue by oliverlockwood** [jenkinsci/groovy-sandbox#57]
If you depend on the latest release shown in the "Releases" tab of this Github repo (currently 1.24) then an `mvn` build shows the following warning:
```
[WARNING] The POM for org.kohsuke:groovy-sandbox:jar:1.24 is missing, no dependency information available
```
and it is necessary to explicitly include the `groovy` dependency as well, because the lack of POM means it is not provided transitively.

Additionally I note that the latest version [visible at Maven Central](https://search.maven.org/search?q=a:groovy-sandbox) is 1.19 (from April 2018).

Is there a specific maven repo that I need to pull artifacts from, or is there some other way to resolve this cleanly?

Many thanks.

**Comment by oliverlockwood** [comment]
Never mind.  I see that this is now hosted at `https://repo.jenkins-ci.org/public/`.

I'll leave the ticket open for now as perhaps it's something that could be made more obvious in the README or docs?  I'd be happy to contribute a PR to this effect if you'd be willing to consider it.

**Comment by dwnusbaum** [comment]
> I'll leave the ticket open for now as perhaps it's something that could be made more obvious in the README or docs? I'd be happy to contribute a PR to this effect if you'd be willing to consider it.

Yes, that would be welcome, see https://github.com/jenkinsci/groovy-sandbox/issues/52#issuecomment-516946768, which I haven't got around to doing yet.
